export enum ActionType {
  FETCH_BOOKS = 'FETCH_BOOKS',
  FETCH_BOOK = 'FETCH_BOOK',
  BOOKS_FETCHED = 'BOOKS_FETCHED',
  BOOK_FETCHED = 'BOOK_FETCHED',
  SELECT_BOOK = 'SELECT_BOOK',
  FETCH_FAVORITES = 'FETCH_FAVORITES',
  FAVORITES_FETCHED = 'FAVORITES_FETCHED',
  UPDATE_FAVORITE_STATUS = 'UPDATE_FAVORITE_STATUS',
  FAVORITE_STATUS_UPDATED = 'FAVORITE_STATUS_UPDATED',
}
